base:
  project_name: used_car_price_prediction
  target: Listed_Price

data_dir:
  artifacts: artifacts
  raw_zip_data_dir: artifacts/raw_zip_data
  raw_zip_data: artifacts/raw_zip_data/Dataset.zip
  raw_csv_data_dir: artifacts/raw_data
  cars_data_clean: artifacts/raw_data/cars_data_clean.csv
  cars_details_merge: artifacts/raw_data/cars_details_merges.csv
  feature_dictionary: artifacts/raw_data/feature_dictionary.csv
  cars_data_final: artifacts/raw_data/cars_data_final.csv
  X_train: artifacts/train_test_data/X_train.csv
  X_test: artifacts/train_test_data/X_test.csv
  Y_train: artifacts/train_test_data/Y_train.csv
  Y_test: artifacts/train_test_data/Y_test.csv

data_cleaning:
  null_thresh: 18907

data_processing:
  year_filter: 2004
model_training:
  best_model: src/utils/objects/best_model.joblib
  object_loc_prefix: src/utils/objects/
  residual_plot: _residuals_plot.png
  feature_importance: _feature_importances.png
  scaler_x: src/utils/objects/scaler_x.joblib
  scaler_y: src/utils/objects/scaler_y.joblib

pickle_files:
  brand_encoding: src/utils/objects/brand.pkl
  model_encoding: src/utils/objects/model.pkl
  state_encoding: src/utils/objects/state.pkl
  owner_type_encoding: src/utils/objects/owner_type.pkl
  body_type_encoding: src/utils/objects/Body_Type.pkl
  transmission_type_encoding: src/utils/objects/Transmission_Type.pkl
  fuel_type_encoding: src/utils/objects/Fuel_Type.pkl
  seller_type_encoding: src/utils/objects/Car_Seller_Type.pkl
  tyre_type_encoding: src/utils/objects/Tyre_Type.pkl
  steering_type_encoding: src/utils/objects/Steering_Type.pkl
  brake_type_encoding: src/utils/objects/Brake_Type.pkl
  drive_type_encoding: src/utils/objects/Drive_Type.pkl
  gear_box_encoding: src/utils/objects/Gear_Type.pkl

